spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: yang6688
    url: jdbc:mysql://localhost:3306/spring-shiro?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Asia/Shanghai
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
